### ISSUE TITLE
Incorrect different number of arguments error

### ISSUE THREAD

**Issue by aakilfernandes** [chriseth/browser-solidity#106] opened 2016-02-22 18:08 UTC
`Error: Different number of arguments in return statement than in returns declaration`

Thrown here:

https://github.com/SafeMarket/grunt-infosphere/blob/infosphered-getters/contracts/simple/infosphered.sol#L55-L57

Which calls:

https://github.com/SafeMarket/grunt-infosphere/blob/infosphered-getters/contracts/simple/Infosphere.sol#L43-L45

Note this seems to happen with bytes and strings, but no other type

**Comment by chriseth** [comment] 2016-02-23 20:32
This is caused by the fact that dynamic types cannot be returned from function calls (limitation of the EVM). Such parameters are removed from the function signature. This can only be fixed by a hard fork of the protocol.

**Closed as completed by chriseth** 2016-02-23 20:32 UTC

**Comment by aakilfernandes** [comment] 2016-02-23 20:44
Got it. Thanks.
