### ISSUE TITLE
NPM installation failure

### ISSUE THREAD

**Issue by pjsample** [chriseth/browser-solidity#66] opened 2015-11-01 02:58 UTC
I'm getting this error when trying to install:

```
npm install solc
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "solc"
npm ERR! node v0.10.25
npm ERR! npm  v3.3.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/x/.npm/solc/0.1.5/package.tgz archive: ENOENT, open '/home/paul/.npm/solc/0.1.5/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/x/npm-debug.log
```

**Comment by croqaz** [comment] 2015-11-02 12:18
Hei, I confirm, I have the exact same error:

```
npm install -g solc 
npm ERR! Linux 3.19.0-31-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "solc"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.8
npm ERR! code EREADFILE

npm ERR! Error extracting /home/cro/.npm/solc/0.1.5/package.tgz archive: ENOENT, open '/home/cro/.npm/solc/0.1.5/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cro/npm-debug.log
```

**Comment by d11e9** [comment] 2015-11-02 12:29
Whats the deal with both referencing `0.1.5` ? most recent is `0.1.6-2` as per https://www.npmjs.com/package/solc

it might be worth trying `npm cache clean`

**Comment by d11e9** [comment] 2015-11-02 12:35
You could also try:

```
npm cache clean
npm install --save solc@0.1.6-2
```

**Comment by croqaz** [comment] 2015-11-02 16:43
Hi @d11e9 ,

Indeed `npm install solc@0.1.6-2` works, but `npm install solc` is trying to install version 1.5...

It's really weird.

**Comment by d11e9** [comment] 2015-11-02 18:52
are you inside a project who's `package.json` specifies to use `0.1.5`? That being said `0.1.5` should still work, will look into reproducing.

**Comment by croqaz** [comment] 2015-11-03 08:28
No, I'm not in any project folder, of course.

I go home, uninstall solc@0.1.6 , install again without any version. Same problem, it's trying to install 0.1.5.

I upgraded NPM to latest version `3.3.12` and still the same thing.

**When installing SOLC manually, it's not a problem.** The problem is when i try to install Embark, because it's a dependency and it's failing to install.

**Comment by chriseth** [comment] 2016-04-15 19:31
Closing this, embark now installs 0.1.6 for me (which is still ancient...).

**Closed as completed by chriseth** 2016-04-15 19:31 UTC
